[theme]
base                     = "light"
primaryColor             = "#1A56DB"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#EEF2FF"
textColor                = "#0D1F52"
font                     = "sans serif"
